import Fa7BrandsBluesky from "virtual:icons/fa7-bands/bluesky";
import Fa7BrandsTwitch from "virtual:icons/fa7-brands/twitch";
import Fa7BrandsTiktok from "virtual:icons/fa7-brands/tiktok";
import Fa7BrandsYoutube from "virtual:icons/fa7-brands/youtube";
import Fa7BrandsGithub from "virtual:icons/fa7-brands/github";
import Fa7BrandsInstagram from "virtual:icons/fa7-brands/instagram";
import Fa7BrandsXTwitter from "virtual:icons/fa7-brands/x-twitter";
import Fa7BrandsPatreon from "virtual:icons/fa7-brands/patreon";
import Fa7BrandsKoFi from "virtual:icons/fa7-brands/ko-fi";
